service: serv-user
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
functions:
  fun-lambda-user-create:
    handler: src/CreateUserHandler.lambdaHandler
    description: Create user
    events:
      - httpApi: POST /user
  fun-lambda-user-get-all:
    handler: src/GetAllUserHandler.lambdaHandler
    description: Get ALl users
    events:
      - httpApi: GET /user/all
custom:
  esbuild:
    bundle: true
    minify: false
plugins:
  - serverless-esbuild
  - serverless-offline