service: service-user-create
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
functions:
  fun-lambda-user-get-all:
    handler: src/GetAllUserHandler.lambdaHandler
    description: Get ALl users
    events:
      - httpApi: Get /user/all
custom:
  esbuild:
    bundle: true
    minify: false
plugins:
  - serverless-esbuild
  - serverless-offline